version: "2"
services:
  mysql:
    image: sordinho/digital_student_record:mysql
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    #        working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=3;ftBE>72h
      - MYSQL_DATABASE=softeng2Final
      - MYSQL_USER=softeng2
      - MYSQL_PASSWORD=3;ftBE>72h
    ports:
      - "8082:3306"
  website:
    image: sordinho/digital_student_record:php
    container_name: php73
    ports:
      - 80:80
    depends_on:
      - mysql
